-- CaFit 테스트용 H2 스키마

CREATE TABLE IF NOT EXISTS users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(50)  NOT NULL UNIQUE,
    password   VARCHAR(100) NOT NULL,
    name       VARCHAR(50)  NOT NULL,
    daily_caffeine_limit  INT          NOT NULL DEFAULT 400,
    caffeine_half_life    DOUBLE       NOT NULL DEFAULT 5.0,
    bed_time              TIME         NOT NULL DEFAULT TIME '23:00:00',
    target_sleep_caffeine DOUBLE       NOT NULL DEFAULT 50.0,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS preset_beverages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    brand_name VARCHAR(50)  NOT NULL,
    category   VARCHAR(30)  NOT NULL,
    volume_ml  INT          NOT NULL,
    caffeine_mg DOUBLE      NOT NULL
);

CREATE TABLE IF NOT EXISTS custom_beverages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    name       VARCHAR(100) NOT NULL,
    category   VARCHAR(30)  NOT NULL,
    volume_ml  INT          NOT NULL,
    caffeine_mg DOUBLE      NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_custom_beverage_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS caffeine_intakes (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT       NOT NULL,
    beverage_name      VARCHAR(100) NOT NULL,
    brand_name         VARCHAR(50),
    category           VARCHAR(30)  NOT NULL,
    volume_ml          INT          NOT NULL,
    caffeine_mg        DOUBLE       NOT NULL,
    consumed_at        TIMESTAMP    NOT NULL,
    source_type        VARCHAR(10),
    source_beverage_id BIGINT,
    CONSTRAINT fk_caffeine_intake_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS favorite_beverages (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT,
    preset_beverage_id BIGINT,
    custom_beverage_id BIGINT,
    display_order      INT    NOT NULL,
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_favorite_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_favorite_preset FOREIGN KEY (preset_beverage_id) REFERENCES preset_beverages (id),
    CONSTRAINT fk_favorite_custom FOREIGN KEY (custom_beverage_id) REFERENCES custom_beverages (id),
    CONSTRAINT uk_favorite_preset UNIQUE (user_id, preset_beverage_id),
    CONSTRAINT uk_favorite_custom UNIQUE (user_id, custom_beverage_id)
);
